#!/usr/bin/expect -f

set arg1 [lindex $argv 0]

spawn ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no pi@$arg1 "mkdir -p /home/pi/.ssh"
expect "assword:"
sleep 1
send "raspberry\r"
interact

spawn scp -o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -r ./ssh/authorized_keys pi@$arg1:/home/pi/.ssh
expect "assword:"
sleep 1
send "raspberry\r"
interact

